[project]
name = "azureml-job-replayer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-ai-ml>=1.26.0",
    "azure-identity>=1.21.0",
    "azureml-mlflow>=1.59.0.post1",
    "jupyter>=1.1.1",
    "mlflow>=2.21.2",
    "mlflow-skinny>=2.21.2",
    "python-dateutil>=2.9.0.post0",
    "tdqm>=0.0.1",
]
